College/Models/CursosModel.cs
using System.ComponentModel.DataAnnotations;

namespace College.Models
{
    public class CursosModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Digite o título do curso")]
        public string Titulo { get; set; }


        [Required(ErrorMessage = "Digite o nome do site que o curso está hóspedado")]
        public string Site { get; set; }


        [Required(ErrorMessage = "Digite a duração do curso")]
        
        public string Duracao { get; set; }


        [Required(ErrorMessage = "Coloque o link do curso")]
        [Url(ErrorMessage = "Link não valido")]
        public string Link { get; set;}


        public string Descricao { get; set;}
    }
}

College/Models/ErrorViewModel.cs
namespace College.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

College/Controllers/CursosController.cs
using College.Models;
using College.Repositorio;
using Microsoft.AspNetCore.Mvc;

namespace College.Controllers
{
    public class CursosController : Controller
    {
        private readonly ICursoRepositorio _cursoRepositorio;

        public CursosController(ICursoRepositorio cursoRepositorio){
            _cursoRepositorio = cursoRepositorio;
        }

        public IActionResult Index() {
            List<CursosModel> cursos = _cursoRepositorio.BuscarTodos();
            return View(cursos);
        }

        public IActionResult Criar() {
            return View();
        }

        public IActionResult Apagar(int id) {

            try {

            bool apagado = _cursoRepositorio.Apagar(id);

                if (apagado) {
                    TempData["MensagemSucesso"] = "Curso apagado com sucesso";
                }
                else {
                    TempData["MensagemErro"] = "Erro ao apagar curso, tente novamente";

                }

                return RedirectToAction("Index");

            }catch (Exception ex) {

                TempData["MensagemErro"] = $"Erro ao cadastrado curso, tente novamente, detalhe do erro: {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        public IActionResult Editar(int id) {
            CursosModel curso = _cursoRepositorio.ListarPorId(id);
            return View(curso);
        }

        public IActionResult ApagarConfirmacao(int id) {
            CursosModel curso = _cursoRepositorio.ListarPorId(id);
            return View(curso);
        }

        [HttpPost]
        public IActionResult Criar(CursosModel curso) {

            try {
                if (ModelState.IsValid) {

                    _cursoRepositorio.Adicionar(curso);
                    TempData["MensagemSucesso"] = "Curso cadastrado com sucesso";
                    return RedirectToAction("Index");

                }

                return View(curso);
            }
            catch (Exception ex) {
                TempData["MensagemErro"] = $"Erro ao cadastrado curso, tente novamente, detalhe do erro: {ex.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Alterar(CursosModel curso) {

            try {
                if (ModelState.IsValid) {
                    _cursoRepositorio.Atualizar(curso);
                    TempData["MensagemSucesso"] = "Curso alterado com sucesso";
                    return RedirectToAction("Index");
                }

                return View("Editar", curso);
            }
            catch(Exception ex) {
                TempData["MensagemErro"] = $"Erro ao alterar curso, tente novamente, detalhe do erro: {ex.Message}";
                return RedirectToAction("Index");
            }

        }
    }
}

College/Controllers/HomeController.cs
using College.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace College.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index() {
            return View();
        }

        public IActionResult Privacy() {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error() {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

College/Views/Cursos/ApagarConfirmacao.cshtml
@model CursosModel
@{
    ViewData["Title"] = "Confirmação de apagar curso";
}
<div class="text-center">
    <h1>Realmente deseja apagar o curso (@Model.Titulo)</h1>
</div>

<div class="d-grid gap-2">
    <a class="btn btn-primary" role="button" asp-controller="Cursos" asp-action="Index">Cancelar exclusão</a>
    <a class="btn btn-danger" role="button" asp-controller="Cursos" asp-action="Apagar" asp-route-id="@Model.Id">Confirmar exclusão</a>
</div>

College/Views/Cursos/Criar.cshtml
@model CursosModel
@{
    ViewData["Title"] = "Adicionar curso";
}

<div class="text-center">
    <h1>Adicionar curso</h1>
</div>

<form asp-controller="Cursos" asp-action="Criar" method="post">

    <div class="mb-3">
        <label for="titulo" class="form-label">Título</label>
        <input type="text" asp-for="Titulo" class="form-control" placeholder="Digite o título do curso">
        @Html.ValidationMessageFor(x => x.Titulo)
    </div>

    <div class="mb-3">
        <label for="site" class="form-label">Site</label>
        <input type="text" asp-for="Site" class="form-control" placeholder="Digite o site do curso">
        @Html.ValidationMessageFor(x => x.Site)
    </div>

    <div class="mb-3">
        <label for="duracao" class="form-label">Duração</label>
        <input type="text" asp-for="Duracao" class="form-control" placeholder="Digite a duração do curso">
        @Html.ValidationMessageFor(x => x.Duracao)
    </div>

    <div class="mb-3">
        <label for="link" class="form-label">Link</label>
        <input type="text" asp-for="Link" class="form-control" placeholder="Coloque o link do curso">
        @Html.ValidationMessageFor(x => x.Link)
    </div>

    <div class="mb-3">
        <label for="descricao" class="form-label">Descrição do Curso</label>
        <textarea asp-for="Descricao" placeholder="Descrição do curso" class="form-control" rows="5"></textarea>
        
    </div>


    <div class="d-grid gap-2">
    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-controller="Cursos" asp-action="Index">Voltar</a>
    </div>

</form>

College/Views/Cursos/Editar.cshtml
@model CursosModel

@{
    ViewData["Title"] = "Editar curso";
}

<div class="text-center">
    <h1>Editar curso</h1>
</div>

<form asp-controller="Cursos" asp-action="Alterar" method="post">

    <input type="hidden" asp-for="Id"/>
    <div class="mb-3">
        <label for="titulo" class="form-label">Título</label>
        <input type="text" asp-for="Titulo" class="form-control" placeholder="Digite o título do curso">
        @Html.ValidationMessageFor(x => x.Titulo)
    </div>

    <div class="mb-3">
        <label for="site" class="form-label">Site</label>
        <input type="text" asp-for="Site" class="form-control" placeholder="Digite o site do curso">
        @Html.ValidationMessageFor(x => x.Site)
    </div>

    <div class="mb-3">
        <label for="duracao" class="form-label">Duração</label>
        <input type="text" asp-for="Duracao" class="form-control" placeholder="Digite a duração do curso">
        @Html.ValidationMessageFor(x => x.Duracao)
    </div>

    <div class="mb-3">
        <label for="link" class="form-label">Link</label>
        <input type="text" asp-for="Link" class="form-control" placeholder="Coloque o link do curso">
        @Html.ValidationMessageFor(x => x.Link)
    </div>

    <div class="mb-3">
        <label for="descricao" class="form-label">Descrição do Curso</label>
        <textarea asp-for="Descricao" placeholder="Descrição do curso" class="form-control" rows="5"></textarea>
    </div>


    <div class="d-grid gap-2">
        <button type="submit" class="btn btn-primary btn-block">Alterar</button>
        <a class="btn btn-secondary btn-block" asp-controller="Cursos" asp-action="Index">Voltar</a>
    </div>

</form>

College/Views/Cursos/Index.cshtml
@model List<CursosModel>
@{
    ViewData["Title"] = "Cursos compartilhados para você";
}

<hearder class="container text-center">
    
    <div class="d-grid gap-3 mb-3 d-md-flex justify-content-md-start">
    <a class="btn btn-primary" role="button" asp-controller="Cursos" asp-action="Criar">Adicionar novo curso</a>
    </div>

    @if(TempData["MensagemSucesso"] != null){
    <div class="alert alert-success" role="alert">
        <button type="button" class="btn btn-danger btn-sm btn-close" ></button>
            @TempData["MensagemSucesso"]
    </div>
    }

    @if (TempData["MensagemErro"] != null) {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm btn-close"></button>
            @TempData["MensagemErro"]
        </div>
    }
    
    <h1>Cursos compartilhados</h1>
    
    <div class="row row-gap ">

        @if(Model != null && Model.Any()) {
            foreach (CursosModel curso in Model) {

                <div class="col col-center">
                    <div class="card sombra" style="width: 18rem; text-align: center">
                        <div class="card-header bg-transparent">
                            <h5 class="card-title">@curso.Titulo</h5>
                        </div>
                        <div class="card-body scroll">
                            <h6 class="card-subtitle mb-2 text-muted">@curso.Site <br> Duração: @curso.Duracao</h6>
                            <p style="max-height: 4rem;">
                               @curso.Descricao
                            </p>
                        </div>
                        <div class="card-footer">
                            <div class="btn-group" role="group" aria-label="Basic example">
                                <a href="@curso.Link" role="button" class="btn btn-success" target="_blank">Acessar</a>
                                <a role="button" class="btn btn-primary" asp-route-id="@curso.Id" asp-controller="Cursos" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger"  asp-route-id="@curso.Id" asp-controller="Cursos" asp-action="ApagarConfirmacao">Apagar</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</hearder>

College/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
    <p>Projeto com o intiuto de compartilhamento de estudos!</p>
 </div>

College/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - College</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/College.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">College</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cursos" asp-action="Index">Cursos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Primeira versão do College
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>